### House_price_regression
##### Anna Tsaturyan

In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

#### Ներմուծենք data-ն

In [14]:
data = pd.read_csv("house_price_regression_dataset.csv")
data

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06
...,...,...,...,...,...,...,...,...
995,3261,4,1,1978,2.165110,2,10,7.014940e+05
996,3179,1,2,1999,2.977123,1,10,6.837232e+05
997,2606,4,2,1962,4.055067,0,2,5.720240e+05
998,4723,5,2,1950,1.930921,0,7,9.648653e+05
999,3268,4,2,1983,3.108790,2,2,7.425993e+05

#### Տեսնենք, թե ինչ data ենք պարունակում

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Square_Footage        1000 non-null   int64
 1   Num_Bedrooms          1000 non-null   int64
 2   Num_Bathrooms         1000 non-null   int64
 3   Year_Built            1000 non-null   int64
 4   Lot_Size              1000 non-null   float64
 5   Garage_Size           1000 non-null   int64
 6   Neighborhood_Quality  1000 non-null   int64
 7   House_Price           1000 non-null   float64
dtypes: float64(2), int64(6)
memory usage: 62.6 KB

#### Համապարփակ ինֆորմացիան նայենք describe-ի միջոցով

In [16]:
data.describe()

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03
mean,2815.422000,2.990000,1.973000,1986.550000,2.778087,1.022000,5.615000,6.188610e+05
std,1255.514921,1.427564,0.820332,20.632916,1.297903,0.814973,2.887059,2.535681e+05
min,503.000000,1.000000,1.000000,1950.000000,0.506058,0.000000,1.000000,1.116269e+05
25%,1749.500000,2.000000,1.000000,1969.000000,1.665946,0.000000,3.000000,4.016482e+05
50%,2862.500000,3.000000,2.000000,1986.000000,2.809740,1.000000,6.000000,6.282673e+05
75%,3849.500000,4.000000,3.000000,2004.250000,3.923317,2.000000,8.000000,8.271413e+05
max,4999.000000,5.000000,3.000000,2022.000000,4.989303,2.000000,10.000000,1.108237e+06

#### Data-ից երևում է (max) արժեքից, որ Num_Bedrooms, Num_Bathrooms, Neighborhood_Quality-ն կարող ենք սարքել int8 տեսակի, իսկ Lot_Size-ը՝ float16

In [17]:
data['Num_Bedrooms'] = data['Num_Bedrooms'].astype("int8")
data['Num_Bathrooms'] = data['Num_Bathrooms'].astype("int8")
data['Neighborhood_Quality'] = data['Neighborhood_Quality'].astype("int8")
data['Lot_Size'] = data['Lot_Size'].astype("float16")

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Square_Footage        1000 non-null   int64
 1   Num_Bedrooms          1000 non-null   int8
 2   Num_Bathrooms         1000 non-null   int8
 3   Year_Built            1000 non-null   int64
 4   Lot_Size              1000 non-null   float16
 5   Garage_Size           1000 non-null   int64
 6   Neighborhood_Quality  1000 non-null   int8
 7   House_Price           1000 non-null   float64
dtypes: float16(1), float64(1), int64(3), int8(3)
memory usage: 36.3 KB

In [19]:
x = data.drop("House_Price", axis = 1)
y = data['House_Price']

#### Կատարենք train_test_split-ը

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.25, random_state=25
)

In [25]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [26]:
y_pred = model.predict(x_test)
y_pred

array([ 150777.57200195,  783030.74058581,  995951.43968299,
        633211.78361829,  251717.48584311,  351443.58928176,
        752396.57855128,  777215.73421575, 1056966.0821899 ,
        936552.76552822, 1103012.87530979,  307438.68971265,
        540253.02290213,  469963.5520509 ,  290607.20109917,
        841266.92152848,  182242.84145425,  309210.27233182,
        406815.04097477,  742706.76923628,  747390.27167249,
        646142.78882301,  834567.93683975,  496114.94481862,
        963577.53737206,  335490.4301864 ,  668800.98395254,
        815113.96520697,  735163.00832784,  681387.27429875,
        600407.94933492,  303956.78057638,  663849.32787025,
        165228.89816337,  417919.70699621,  676125.76930432,
        729417.01781959,  511693.25294927,  331360.94380241,
        529314.60094886,  717766.78851339,  549689.52891567,
        960102.16070949,  855548.64740575,  853038.37277791,
        405101.84155744,  505256.39651808,  449777.97329846,
        137329.58363362,  198618.00973625,  970687.80071743,
        387942.31050097,  541446.39498947,  891431.54209449,
        630697.04174209,  511923.24273665,  692812.4554005 ,
        334739.12042533,  895861.23675165, 1026637.20099713,
        135972.62660031, 1059100.20027689,  538662.90247167,
        560200.83093183,  678583.1090654 ,  320817.89284744,
       1025884.39417908,  558863.33994967,  210970.2236105 ,
        661424.85630202,  592627.63651996,  467628.58870324,
        879899.48183308,  663532.09488214,  543324.36139232,
        592572.74428453, 1082501.23024486,  516605.8481292 ,
        648354.0300874 ,  435379.87331193,  697595.006126  ,
        863995.07965435,  977023.70790289,  429869.75924806,
        574128.12903115,  872075.97386288,  621814.89426188,
        165431.09395607,  279811.59501096,  512123.93517936,
        879754.83084406,  699709.33497494, 1096943.14871106,
        861561.23220909,  518322.09057954,  503984.12060037,
        649394.17260567,  388587.7124519 ,  558019.52275441,
        909574.31934135,  428925.12242191,  821583.37716574,
        328871.15391988,  126438.01572338,  898770.23052287,
        861207.52676759,  783682.28278037,  386228.36043275,
        961900.96216867,  341680.01690661,  560943.25609369,
        716718.32824038,  313084.73291964, 1050494.54703033,
        304795.36555048,  868553.57188015,  355584.47480311,
        690120.58873218,  545616.87805077,  821531.74736323,
        333495.95534821,  504484.67163739,  985807.70827952,
        740280.24217884,  987918.15956302,  348146.41689474,
        732334.34192018,  488859.52350796,  882589.80445371,
        551267.22185614,  288609.60951198,  475396.33991313,
        459495.3145687 ,  650066.62920669,  212683.05115196,
        663248.41792691,  423594.15475379,  451969.54327176,
        257443.19672929,  687553.00976744,  801292.51830819,
        460923.44728002,  621630.36997348,  404095.8249494 ,
        857118.30622797,  492121.27679177,  833710.88009553,
        734930.13119501,  337594.44291966, 1035070.58608605,
        281533.45610135,  282273.72981409,  190146.93782501,
        718080.29970015,  918319.89724123, 1040029.52032934,
        845800.67622838,  795342.37881821, 1008121.77502833,
        497436.35671075,  548730.45537786,  831420.60091635,
        529659.26258528,  761491.19593819,  378149.6188088 ,
        856906.24332908,  553892.24358708,  943195.2462752 ,
        352258.1621112 ,  613998.9358667 ,  573520.7206714 ,
        231574.46714994,  777220.64149669,  751973.29547493,
        531966.83785813,  242442.07391012,  232775.49613246,
        378972.67488605, 1016913.94685365,  688983.81411911,
        615781.77613531,  928629.65407325,  263829.31180616,
       1056619.16083716,  220481.41069788,  363763.05963868,
        705195.18136617,  397856.70465354,  378300.25187316,
        731696.8064738 ,  248786.98844746,  944978.95422042,
        281330.39518502,  651318.06675881,  504777.82931956,
        457192.14577282,  974862.54615256,  880381.72472883,
        706514.41558229,  993219.73130573,  687652.01076343,
        931232.7180494 ,  994654.19751291, 1049358.63442071,
        403543.97353155, 1012699.85139988,  525751.80925642,
        542916.93657558,  851760.56902334,  726304.06566582,
        755242.65388526,  931708.37157442,  947306.03449645,
        913900.79436296, 1023769.89629015,  513741.33496234,
        303080.99340565,  657182.71894626, 1018536.46930539,
        627342.11151133,  981586.05194209,  911623.72326511,
       1083869.19311794,  456480.98721811,  507316.72199512,
        252634.52626612,  916024.10587249,  524248.17524308,
        336104.33007867,  867143.61757866,  858907.22997756,
        424037.56970205,  819274.76534414,  993061.79554695,
        755891.722552  ,  280079.11596225,  743304.49039119,
        225282.19104603,  519485.55948164,  988311.44622547,
        701687.75474705,  649584.76416532,  606403.4800599 ,
        634778.92801403,  240422.7415551 ,  729869.24010669,
        740588.36614675,  775163.48381478,  161002.32505521,
        681807.69682462])

In [28]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

#### Հաշվենք հետևյալ գործակիցները․

In [30]:
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f'mse = {mse}\nmae = {mae}\nr2 = {r2}')

mse = 104300673.7454386
mae = 8150.452412978487
r2 = 0.9984021303393092

#### Մոդելի միջին բացարձակ սխալը (MAE) կազմում է 8150, ինչը նշանակում է, որ մոդելը տան գինը միջինում սխալվում է մոտ 8150 միավորով։ R² ցուցանիշը հավասար է 0.9984, ինչը նշանակում է, որ մոդելը բացատրում է գների տատանումների մոտ 99.8%-ը։

In [34]:
b_0, k_0 = model.intercept_, model.coef_
b_0, k_0

(np.float64(-1978866.5565254036),
 array([  199.67301274,  9913.35063166,  8375.74512477,   977.74117917,
        14958.43861078,  5360.77530971,    70.30989973]))